package:
  name: deps
  version: "0.0.1"

build:
  script: python setup.py install

requirements:
  build:
    - pyyaml
  run:
    - pyyaml

source:
  path: ../

about:
  home: https://github.com/malev/deps
